### ISSUE TITLE
(More a question than bug report)

### ISSUE THREAD

**Issue by Just-another-pleb** [sparkfun/OpenLCD#25]
I don't know an easier way to get in touch with you about this display.
I use Node-Red on a RasPi.

I have a display which I have been told is covered by this bit of software.

Alas I think what you have is for Arduinos / etc, and not for Node-Red.

No problem.

The RasPi and the display are 3.3v, so that is good.
I got it, hooked it up and used someone else's *node* but it would seem I have opened a can of hurt.

I am wanting a node to talk to this display and send it commands like:
backlight (on/off)
cursor (on/off)
blink (on/off)
and x/y positioning for text.
Though if the x/y is missing, it just prints at the next position.

Could you help me?

**Comment by fourstix** [comment]
Hi,
I have only played with Node-Red a little bit, but I think what you want to do is to create a custom node for the LCD.   Node-Red has a page how to create custom nodes for a component.  You could use the same commands as in the Arduino based code to control the OpenLCD in your custom node.

There's a guide on creating a new node available here:
https://nodered.org/docs/creating-nodes/

Once you've created the node and tested it.  I believe you can publish it so other Node-Red users can use it.

Good luck,
Gaston

**Comment by Just-another-pleb** [comment]
I was kind of hoping that someone else had done that, but their I2C address is 27 but on the RasPi when I scan for it: it shows at address 72.

Thanks.

I think I can *back engineer* it if I look hard and long enough at the Arduino code and the code for the existing node - which has the wrong address.

Thanks though.

I may still need your help.   (If you don't mind)

**Comment by Just-another-pleb** [comment]
I am still not really getting any useful/helpful replies from SparkFun on the specs of this.

However, reading what I can find, and what is in this .... system, it should work but isn't.

The display (and AVR) come with this .... _QWIIC_ already loaded.
Looking at that, QWIIC is something to do with the I2C bus.   Great!

We've been over that.   That is how I am connecting it to the RasPi.

But when I start going into that stuff, all the links loop back on themselves.  Which isn't helpful.

In this software I have seen python code to do things.   But is that code run on .....   Where?  On the AVR or the machine connected to the display?

It is confusing to me what is going on.

**Comment by nseidle** [comment]
Sorry for the confusion. This repo is the firmware that is loaded onto our displays. It's written in C.

What you are asking for is assistance with the Python code that you will want to run on your RPi. Please see this [repo](https://github.com/sparkfun/Qwiic_SerLCD_Py) and consider posting an issue there.

**Comment by Just-another-pleb** [comment]
My problem is that the firmware flashed into the firmware is buggy.

When I change the backlight value a message is printed on the screen informing me of this.

Ok, nice if that would be helpful to me, but it isn't and it causes confusion with the scripts running.

It would be nice if this _feature_ could be disabled.

So what I am (now) looking for is the firmware loaded into the display so I can modify it to not do what it is doing.

Oh, and running the demo scripts that come from Sparkfun on how to use it.
Horrible.

Example 2 and 13.

One of them waits 5 seconds between colour changes.  The other 2 seconds.

Weirdly the one which waits 2 seconds works.  The one which waits 5 seconds the colour names and the colours shown are very much out of sync.

I have a video of this happening but it is 3.9 Mb and I am not sure I can upload that type of file and one of that size.
