### ISSUE TITLE
Erroneous messages on display when adjusting back light

### ISSUE THREAD

**Issue by Just-another-pleb** [sparkfun/OpenLCD#26]
After a lot of work, I got the display working.

Attached video explanation:

The display is showing me the time/date/day of week.
And there are a couple of problems visible that the messages are not quite working as they get their positions wrong now and then.
(That's probably an I2C noise issue.  But it is not this problem)

So the display has a _backlight_ of 255,255,255.  Though the colour is not exactly correct as you see it, I think that is more to do with the angle at which is it viewed.   However, the problem will become apparent when you continue watching the video.

I have opened a python (2.x) shell and typed in all but the last command shown here, now.
There is **no** implication that python3.x is supported or there is even a 3.x package available.

`
pi@alarmclock:~/.node-red$ python
Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import print_function
>>> import qwiic_serlcd
>>> import time
>>> import sys
>>> myLCD = qwiic_serlcd.QwiicSerlcd()
>>> myLCD.setBacklight(150,0,0)
`

You see the display happily showing the time.

I enter the last line:  `myLCD.setBacklight(150,0,0)` and watch what happens.

The display colour changes.  Not once, not twice but many times.
Simply from me entering the ONE command.

Also see ~~the~~ a colour name top left.
Nothing to do with the colour of the backlight.
Then towards the end you see the screen is covered with numbers.
My suspicion is that is the time being _forced_ all over the place.

So, problems - as I see them:
- There is a `backlight` command.  You enter it with a `r,g,b` parameter and it shows you a whole bunch of back ground colours.
- When the back ground colour is adjusted a random/nominal colour name is printed on the screen.  Top left.
- I have tried the `contrast` command and looking at the screen, I can't see any changes.
It isn't documented how to use other than something like:  _The lower the number, the higher the contrast._
Ok, so if you want a high contrast display, enter `0` - I guess.
It doesn't say if the LOWEST number is `0` or `1`.
And what is the highest number?
(Maybe this is a documentation problem and not for here, but I am quite happy to create a bug report there **IF** I can find the link.)

[LCD.zip](https://github.com/sparkfun/OpenLCD/files/5152699/LCD.zip)

**Comment by fourstix** [comment]
>There is no implication that python3.x is supported or there is even a 3.x package available.

There's a Circuit Python library written in Python 3 available for this display. The Arduino examples are available as examples in the Circuit Python library.

 Information and install instructions are available here:  https://github.com/fourstix/Sparkfun_CircuitPython_SerLCD

**Comment by Just-another-pleb** [comment]
I am connecting the display - out of the box - to a RasPi.

After messing around and many trips down wasteful links I discovered I had to install SparkFun's qwiic package.

The display then started to work as a display.

It came with a heap of example python files which were nice and did help me get things to where they are/were on the video clip.

But when it comes to adjusting the back light:  all bets are off.

I was _sent here_ because I was showing people how I was talking to the display using `python2.7`.

**you have to use `pythono3.x**

This entire scenario is not nice.
The display is great - in the concept of a display - but when it comes to the firmware showing messages on the screen when I send it a command to adjust the back light is just unbelievable.

And that the colour it says is not exactly related to the colour shown.   That's just not acceptable.

I shall try that new link and see what happens.

Thanks.

**Comment by Just-another-pleb** [comment]
I have to say:  At least you **are** helping me.

Sparkfun are **NOT**.

The problem now is that the original lot of stuff I got - for 2.7 - had a lot of example scripts which I could then deconstruct and get the commands to do what I want.

Although there is a *demo script* it assumes all the other boards are there and needs a new kind of MQTT (from what I could read).

Where can I get a list of the commands I can use in Python3.x to talk to the display?

Thanks in advance.

**Comment by fourstix** [comment]
I would suggest looking at the python libraries to see how they send commands to the display.  

You can take a look inside  the file [sparkfun_serlcd.py](https://github.com/fourstix/Sparkfun_CircuitPython_SerLCD/blob/master/sparkfun_serlcd.py) to see how the CircuitPython library I wrote sends commands to the display.  If you want to see how to send the command's yourself, you will need to go digging.

But the easiest thing to do is to install a library either Sparkfun's Qwiic_Py library or Adafruit's CircuitPython library and then use the library class for the device to handle the commands.   I wrote the CircuitPython library because I wanted to mix and match Sparkfun and Adafruit components in CircuitPython.

Good luck to you!

**Comment by Just-another-pleb** [comment]
I have installed the library - or I hope I have.

That is this one - yes?    [https://github.com/fourstix/Sparkfun_CircuitPython_SerLCD](url)

Done, but I am at a loss where the commands are _defined_

Though I am not really able to decode them.   I am able to see it _better_ when they are in code and I can see the structure that way.

What also derails any possibility of me understanding anything is that once I installed the library with the pip3 command, and I `cd` to it and then into the directory for the display - or the one I think is it - there are some files:
`INSTALLER` `LICENSE` `METADATA` `RECORD` and so on.

`INSTALLER` says `pip` and not `pip3`.

All my problems are because I used `pip` to install things and not `pip3`.
To install this I had to use `pip3`.

Why/how is it _LEGAL_ (you tell me a better word) for software which needs to be installed with `pip3` to then use `pip`?

**Comment by fourstix** [comment]
Depends on how your Raspbian is set up.  Pip3 is always Python3 but the default Pip can point to either Python 2.7 or 3.

If you click on the link in the highlighted file name in my previous message that will take you directly to the source code file on GitHub and you  can see the actual code there.  Viewing the source file on GitHub is often easier to me, than digging in the directory structure :-)

**Comment by Just-another-pleb** [comment]
Yes, I went there.  Thanks.

But I am not able to see the commands as I explained in the other post.

Example scripts are wonderful for me, as I again explained.   I know there is a base line of what the command is and expects.
But reading the source code and trying to extrapolate the command fails for me miserably.

You didn't explain the `INSTALLER` and why it says `pip` and not `pip3`.
I did see the "Depends on how the raspi is set up", but if I am told I need to install it with pip3 because pip installs the wrong version, then the version that is installed also needs to use pip3.

It can't use pip, otherwise when I did the `pip`, I would have installed/got this version, not the older one.

Anyway, moving on:
(In case I didn't say it)

I wrote a flow (Node-Red) that worked with python2.7 the display *worked*.

After installing this and running python3 <script> the display is blank, but I know the script is running as I run it from a CLI and it is running.

Therefore:  The commands have been changed form the 2.7 version.
Annoying, but I accept you wanted it to be more modular - or something like that.

So I need to see the commands so I can modify the script (python) to use the new commands.

**Comment by Just-another-pleb** [comment]
Good news.  Bad news.
Well, honestly that is what it is.

I don't know what/why or anything else.

I did the stuff again (there is a sever feeling of De Ja Vous) but for python3.

All the stuff.....

The node-red flow didn't show anything when run.

Honestly.  I don't know.

The flow is now working.

But the original problem persists:

When I change the background colour, the display shows/scrolls through several colours and there are messages printed on the screen which were not asked for by me.

I'll now go to the newer link and post there.

**Comment by Just-another-pleb** [comment]
Oh sorry.   Closed now.
