### ISSUE TITLE
Characters being deleted when changing backlight?

### ISSUE THREAD

**Issue by Faeranne** [sparkfun/OpenLCD#28]
Getting a weird bug whenever I try to change the backlight over I2C.  Any time I do so, the screen will delete a character, usually the last one from the current message, though repeating the change will delete more and more characters.   Any idea why this is happening?

**Comment by nseidle** [comment]
Thanks for reporting. Do you have example code that demonstrates the issue so we can reproduce?

**Comment by Faeranne** [comment]
```
import qwiic_serlcd
lcd = qwiic_serlcd.QwiicSerlcd()
lcd.begin()
lcd.setContrast(5)
lcd.clearScreen()
lcd.print("Hello World")
lcd.setBacklight(0,0,0)
#'d' should now disappear from 'World'
lcd.setBacklight(100,100,255)
#'l' should now disappear from 'World'
```

Tested on python3 with `Qwiic_SerLCD_Py` installed.

**Comment by nseidle** [comment]
Ah, this repo is the firmware that runs on the LCD. I suspect it's python library related. I've moved your issue to [that repo](https://github.com/sparkfun/Qwiic_SerLCD_Py/issues/4).

**Comment by Faeranne** [comment]
I've had the same issue with an arduino setup as well... Originally thought it was the arduino library, so I tested it with the above python.

**Comment by nseidle** [comment]
Ok, feel free to post an example problem sketch on the [Arduino library](https://github.com/sparkfun/SparkFun_SerLCD_Arduino_Library/issues). If we pin it down to firmware on the LCD, then... well, I'll move some issues again :)
