### ISSUE TITLE
Libraries for Reuploading the Default Firmware

### ISSUE THREAD

**Issue by bboyho** [sparkfun/OpenLCD#3]
It would be nice to include the additional libraries used for the default firmware in the repository. =) If not, it would be nice to include a link them somehow. I bricked the OpenLCD when trying to upload code to another Arduino. The pins were on the same hardware UART line. Doing a search online, I found the libraries:

SoftPWM library => https://code.google.com/p/rogue-code/wiki/SoftPWMLibraryDocumentation#Download

LiquidCrystalFast library from PJRC => https://www.pjrc.com/teensy/td_libs_LiquidCrystal.html

**Comment by fourstix** [comment]
The link for the SoftPWM library in @bboyho 's comment now gives a 404 error.  It looks like the latest version of SoftPWM is now here on github https://github.com/bhagman/SoftPWM , also one can install SoftPWM through the 
FWIW,  I second the suggestion to put links in the tutorial.  Also it may be possible to install these Libraries through the Arduino Library manager.  That might be the easiest thing to do.

**Comment by fourstix** [comment]
(I don't know why github word-wrapped my comment like that. It should say:)
The link for the SoftPWM library in @bboyho 's comment now gives a 404 error. 
It looks like the latest version of SoftPWM is now here on github https://github.com/bhagman/SoftPWM , also it may be possible to install these Libraries through the Arduino Library manager.  
FWIW, I second the suggestion to put links in the tutorial.

**Comment by bboyho** [comment]
If anyone needs to reupload OpenLCD's default firmware, the zipped libraries have been linked in the [Troubleshooting section](https://learn.sparkfun.com/tutorials/avr-based-serial-enabled-lcds-hookup-guide/troubleshooting) of the tutorial. I followed the "**Add .ZIP Library...**" route since the _Liquid Crystal Fast Library_ does not appear to be in GitHub or included in the Arduino IDE's Library Manager.
