### ISSUE TITLE
Display Customer Character function accepts 9 when only 8 custom characters are allowed.

### ISSUE THREAD

**Issue by fourstix** [sparkfun/OpenLCD#5]
Issue:
Fence Post error (Off by one error) in OpenLCD.ino, line 226, display customer character function.
Fix:  
Change the upper limit from 43 to 42, the if statement should allow 35 to 42, inclusive since only 8
customer characters may be defined.
Severity: Low/4/Might Fix
Justification:  
The underlying function will map the invalid request for customer character 9 to custom character 0, so the impact is minimal.  Fixing this problem may make the code more robust and prevent possible future problems.

Obligatory XKCD reference:
https://xkcd.com/1110/
Click and drag the last panel to reveal the following text:
If you are having fence post errors,
I feel bad for you son -
I got 99 problems, but
somehow solved 101.

**Comment by fourstix** [comment]
Oops, I should have typed line 266. This line
else if (incoming >= 35 && incoming <= 43)
should be
else if (incoming >= 35 && incoming <= 42)
instead.

**Comment by nseidle** [comment]
Wow that's an awesome XKCD! Had not seen that one.

Good find and thanks for the PR #7. Closing this issue.
