### ISSUE TITLE
Add function for printing the pipe character to the serLCD display

### ISSUE THREAD

**Issue by fourstix** [sparkfun/OpenLCD#8]
Currently pipe | is used as the command setting character, and printing a string with a pipe character may accidentally invoke a display function.  There currently is no way to print a string with a pipe character to the display.

Adding logic to allow pipe to be double escaped || would allow the user to print a pipe symbol as a character in a string without accidentally invoking a display command.

**Comment by nseidle** [comment]
Yup! You fixed this in PR #7. Rock on and thanks for the help! Please let me know if you see anything else that needs fixing.
